// SOI — Operational Narrative Intelligence
// Phase 15: Explainable operational summarization from memory.
//
// RULES:
//   1. Pure functions — deterministic, replay-safe
//   2. Narratives derived from operational facts, not generated by AI
//   3. Every statement traceable to specific events/conditions
//   4. Calm, precise, operationally grounded language
//   5. No chatbot AI, no generative text
//
// Generates: shift narratives, stabilization summaries, pressure
// evolution descriptions, escalation chain analysis.

import type { Incident, RecoveryAction } from './lifecycle-types';
import type { SoiEvent } from '@/lib/soi-types';
import type { OperationalStabilityIndex } from './anticipatory-cognition';
import type { ShiftContext } from './auth-identity';

// ============================================================
// TYPES
// ============================================================

export interface OperationalNarrative {
  /** Narrative type */
  type: 'shift_summary' | 'pressure_evolution' | 'escalation_chain' | 'recovery_analysis' | 'institutional_observation';
  /** The narrative text */
  text: string;
  /** Time span this covers */
  period: { start: string; end: string };
  /** Supporting evidence count */
  evidenceCount: number;
  /** Confidence qualifier */
  qualifier: 'observed' | 'pattern-based' | 'limited-history';
}

// ============================================================
// NARRATIVE ENGINE
// ============================================================

/**
 * Generate operational narratives from operational memory.
 * Pure function — deterministic, replay-safe.
 */
export function generateOperationalNarratives(
  incidents: readonly Incident[],
  recoveryActions: readonly RecoveryAction[],
  events: readonly SoiEvent[],
  stability: OperationalStabilityIndex,
  shiftContext: ShiftContext,
  asOf?: Date,
): OperationalNarrative[] {
  const now = asOf ?? new Date();
  const narratives: OperationalNarrative[] = [];
  const windowStart = new Date(now.getTime() - 4 * 60 * 60_000);

  // ── Shift summary ──
  const shiftIncidents = incidents.filter(i =>
    new Date(i.opened_at).getTime() >= new Date(shiftContext.startedAt).getTime()
  );
  const resolved = shiftIncidents.filter(i => i.resolved_at);
  const unresolved = shiftIncidents.filter(i => !i.resolved_at && !i.closed_at);
  const critical = shiftIncidents.filter(i => i.severity === 'CRITICAL');
  const escalated = events.filter(e =>
    e.event_type.includes('escalation.requested') &&
    new Date(e.created_at).getTime() >= new Date(shiftContext.startedAt).getTime()
  );

  if (shiftIncidents.length > 0) {
    const parts: string[] = [];
    parts.push(`${shiftIncidents.length} incident${shiftIncidents.length !== 1 ? 's' : ''} during current shift.`);
    if (resolved.length > 0) parts.push(`${resolved.length} resolved.`);
    if (unresolved.length > 0) parts.push(`${unresolved.length} remain unresolved.`);
    if (critical.length > 0) parts.push(`${critical.length} at CRITICAL severity.`);
    if (escalated.length > 0) parts.push(`${escalated.length} escalation${escalated.length !== 1 ? 's' : ''} requested.`);
    if (shiftContext.inheritedIncidentCount > 0) parts.push(`${shiftContext.inheritedIncidentCount} inherited from prior shift.`);

    narratives.push({
      type: 'shift_summary',
      text: parts.join(' '),
      period: { start: shiftContext.startedAt, end: now.toISOString() },
      evidenceCount: shiftIncidents.length,
      qualifier: 'observed',
    });
  }

  // ── Pressure evolution ──
  const pressureParts: string[] = [];
  if (stability.direction === 'destabilizing') {
    const degrading = stability.components.filter(c => c.trend === 'degrading');
    pressureParts.push(`Operational conditions showing degradation in ${degrading.length} area${degrading.length !== 1 ? 's' : ''}: ${degrading.map(c => c.name.toLowerCase()).join(', ')}.`);
  } else if (stability.direction === 'stabilizing') {
    pressureParts.push('Operational conditions improving toward stability.');
  } else if (stability.direction === 'acute') {
    pressureParts.push('Multiple operational systems under simultaneous strain. Coordination capacity may be exceeded.');
  }

  if (pressureParts.length > 0) {
    pressureParts.push(`Overall pressure: ${stability.overallPressure}/100. Duration: ${stability.durationMin}m.`);
    narratives.push({
      type: 'pressure_evolution',
      text: pressureParts.join(' '),
      period: { start: windowStart.toISOString(), end: now.toISOString() },
      evidenceCount: stability.components.length,
      qualifier: 'observed',
    });
  }

  // ── Escalation chain analysis ──
  const escalationRequests = events.filter(e => e.event_type.includes('escalation.requested'));
  const escalationAcks = events.filter(e => e.event_type.includes('escalation.acknowledged'));
  if (escalationRequests.length > 0) {
    const acked = escalationAcks.length;
    const unacked = escalationRequests.length - acked;
    const parts: string[] = [];
    parts.push(`${escalationRequests.length} escalation request${escalationRequests.length !== 1 ? 's' : ''} in operational history.`);
    if (acked > 0) parts.push(`${acked} acknowledged.`);
    if (unacked > 0) parts.push(`${unacked} pending response.`);

    // Escalation response timing
    if (acked > 0) {
      const responseTimes: number[] = [];
      for (const req of escalationRequests) {
        const ack = escalationAcks.find(a =>
          a.entity_id === req.entity_id &&
          new Date(a.created_at).getTime() > new Date(req.created_at).getTime()
        );
        if (ack) {
          responseTimes.push((new Date(ack.created_at).getTime() - new Date(req.created_at).getTime()) / 60_000);
        }
      }
      if (responseTimes.length > 0) {
        const avg = Math.round(responseTimes.reduce((s, t) => s + t, 0) / responseTimes.length);
        parts.push(`Average escalation response: ${avg}m.`);
      }
    }

    narratives.push({
      type: 'escalation_chain',
      text: parts.join(' '),
      period: { start: windowStart.toISOString(), end: now.toISOString() },
      evidenceCount: escalationRequests.length,
      qualifier: 'observed',
    });
  }

  // ── Recovery analysis ──
  const allActions = recoveryActions;
  const completed = allActions.filter(a => a.status === 'COMPLETE');
  const blocked = allActions.filter(a => a.status === 'BLOCKED');
  const withdrawn = allActions.filter(a => a.status === 'WITHDRAWN');

  if (allActions.length > 0) {
    const parts: string[] = [];
    parts.push(`${allActions.length} recovery action${allActions.length !== 1 ? 's' : ''} in operational history.`);
    parts.push(`${completed.length} completed, ${blocked.length} blocked, ${withdrawn.length} withdrawn.`);

    if (blocked.length >= 2) {
      parts.push('Multiple blocked recovery actions may indicate systemic resource constraints.');
    }
    if (withdrawn.length >= 2) {
      parts.push('Multiple withdrawn actions suggest initial recovery approaches were not viable under current conditions.');
    }
    const successRate = allActions.length > 0 ? completed.length / allActions.length : 0;
    if (successRate < 0.5 && allActions.length >= 3) {
      parts.push(`Recovery success rate (${Math.round(successRate * 100)}%) below 50% — coordination structure may need review.`);
    }

    narratives.push({
      type: 'recovery_analysis',
      text: parts.join(' '),
      period: { start: windowStart.toISOString(), end: now.toISOString() },
      evidenceCount: allActions.length,
      qualifier: 'observed',
    });
  }

  // ── Institutional observation ──
  const reassignments = events.filter(e => e.event_type.includes('reassigned'));
  const ownershipTransfers = events.filter(e => e.event_type.includes('handoff'));
  if (reassignments.length + ownershipTransfers.length >= 2) {
    narratives.push({
      type: 'institutional_observation',
      text: `${reassignments.length} reassignment${reassignments.length !== 1 ? 's' : ''} and ${ownershipTransfers.length} handoff${ownershipTransfers.length !== 1 ? 's' : ''} recorded. Coordination ownership has been actively managed during this operational window.`,
      period: { start: windowStart.toISOString(), end: now.toISOString() },
      evidenceCount: reassignments.length + ownershipTransfers.length,
      qualifier: 'observed',
    });
  }

  return narratives;
}
