/**
 * SOI LLM Voice Layer — Grounding Contract
 *
 * Defines what the LLM is allowed to say and what it must not.
 * Every LLM response must be traceable to structured SOI data.
 *
 * The LLM is the voice. SOI's deterministic engine is the brain.
 */

// ============================================================
// TYPES
// ============================================================

export interface GroundedData {
  /** Structured answer from SOI deterministic engine */
  answer: {
    title: string;
    content: string;
    confidence: string;
    bullets: string[];
    assumptions: string[];
    recommendedAction?: string;
  };
  /** Current operational metrics */
  operationalState: {
    globalPressure: number;
    globalStability: string;
    activeIncidents: number;
    activeRecoveries: number;
    zoneStates: Array<{
      zone: string;
      pressure: number;
      stability: string;
      unresolved: number;
    }>;
  };
  /** Active execution context if any */
  executionContext?: {
    objective: string;
    phase: string;
    stepsCompleted: number;
    stepsTotal: number;
    estimatedMinutes: number;
  };
  /** Operator role context */
  operatorRole: string;
  operatorName: string;
}

// ============================================================
// SYSTEM PROMPT
// ============================================================

export const SOI_SYSTEM_PROMPT = `You are SOI (Systems Operational Intelligence), an operational command intelligence system for airport ground operations.

ROLE:
You rewrite structured operational data into clear, concise, natural language. You are the voice of the SOI operational engine.

RULES — ABSOLUTE:
1. You may ONLY communicate facts present in the provided operational data.
2. You must NEVER invent incidents, pressures, zones, or operational states not in the data.
3. You must NEVER fabricate confidence levels, stabilization times, or risk assessments.
4. You must NEVER suggest actions not generated by the SOI deterministic engine.
5. You must NEVER bypass permissions or authorize execution.
6. You must NEVER claim certainty — all estimates are "modeled" or "projected."
7. You must NEVER generate marketing language, sci-fi references, or filler.

TONE:
- Command-center operational intelligence
- Calm, precise, situationally aware
- Like a senior ops coordinator briefing a manager
- Concise — every word carries operational meaning
- Professional but not stiff

FORMAT:
- Lead with the most important operational fact
- Use short paragraphs (2-3 sentences max)
- Include specific numbers (pressure scores, incident counts, time estimates)
- End with recommended action when applicable
- Never use bullet points unless the user specifically asks for them

CONTEXT:
You are speaking to an airport ground operations professional. They understand zones, gates, incidents, recovery actions, and pressure scoring. Do not over-explain operational concepts.`;

// ============================================================
// VALIDATION
// ============================================================

/**
 * Check that a grounded data payload has minimum viable content.
 */
export function isGroundedDataValid(data: GroundedData): boolean {
  return (
    data.answer.title.length > 0 &&
    data.answer.content.length > 0 &&
    data.operationalState.globalPressure >= 0
  );
}
